### ISSUE TITLE
Fork repos are not working after changing cdn url

### ISSUE THREAD

**Issue by viper-adnan** [Aicirou/goindex-theme-acrou#156]
**Forked repos are not working here what I did..**
1. Forked your repo
2. Changed `eyes.png` in public and dist both directories.
3. Changed cdn url in 
      `dist/index.html`
      `.env`
      `dist/app.js`
4. Made a new release [`v2.0.9`](https://github.com/viper-adnan/goindex-theme-acrou/releases)
5. Changed cdn url in my cloudflare worker.
6. Tried clearing cache 
7. Checked in cloudflare worker preview

**But eyes.png not changed.**

**Comment by Aicirou** [comment]
1、change 
https://github.com/Aicirou/goindex-theme-acrou/blob/facd77d7f9bc2858d2f50636b0b7ac4311fe402e/src/views/common/Navbar.vue#L110

2、npm run build

**Comment by viper-adnan** [comment]
> 1、change
> https://github.com/Aicirou/goindex-theme-acrou/blob/facd77d7f9bc2858d2f50636b0b7ac4311fe402e/src/views/common/Navbar.vue#L110
> 
> 2、npm run build

Hey, Thanks for quick reply !
But is there need to change any other cdn url (except in index.js)
Means I changed it in my cloudflare worker. Can you tell the path of other files where I have to change it ? Thanks.

**Comment by Aicirou** [comment]
1. change `cdn` in `.env`
2. npm run build
3. submit code
4. change `version in` `package.json` (optional)
4. release (optional)
2. change `cdn` and `version` in `workers`

**Comment by viper-adnan** [comment]
> 1. change `cdn` in `.env`
> 2. npm run build
> 3. submit code
> 4. change `version` in `package.json` (optional)
> 5. release (optional)
> 6. change `cdn` and `version` in `workers`

Worked thanks 🖤 !
I uses these steps...

1. Forked Repo
2. Edit changes
3. Upgrade version in `package.json`
4. Run `$ npm install`
5. Run `$ npm run build`
6. Add all changes to git.
7. Commit changes and push.
8. Release a new version same as you edited in step 3.
9. Update `cdn` and `version` in your cloudflare worker `themeOptions`
10. Deploy and Enjoy.
