### ISSUE TITLE
JS代码插入百度统计？请问想法是什么？

### ISSUE THREAD

**Issue by Theotimus** [Aicirou/goindex-theme-acrou#170]
https://cdn.jsdelivr.net/gh/Aicirou/goindex-theme-acrou@v2.0.8/dist/js/app.da7f5f3f.js

![baidu](https://i.loli.net/2020/10/30/pQ6TlZYR45vEJe2.png)

https://hm.baidu.com/hm.js?6be1011f95a1bfcdb2179fe2ae6e58fe

**Comment by Aicirou** [comment]
![image](https://user-images.githubusercontent.com/32474991/97657992-36ba3b80-1aa6-11eb-91e5-0284ebedafce.png)

**Comment by MFYDev** [comment]
+1同问
