### ISSUE TITLE
Empty driver

### ISSUE THREAD

**Issue by Antxj** [Aicirou/goindex-theme-acrou#4]
![image](https://user-images.githubusercontent.com/92764157/161452645-1b1dc3f3-fb5f-439c-a983-6a2690595843.png)

![image](https://user-images.githubusercontent.com/92764157/161452659-2780d8cb-a2ef-40f6-a421-439200c901a2.png)

**Comment by sardine9** [comment]
same problem

**Comment by shy2000** [comment]
You can try to get the refresh_token manually
