### ISSUE TITLE
播放判断

### ISSUE THREAD

**Issue by jzysl123** [Aicirou/goindex-theme-acrou#4]
windows访问播放目前是iina://weblink?url=
可以加个判断windows为potplay嘛 potplayer:// 
类似这个修改版https://github.com/yanzai/goindex 电脑和手机端会自动判断选择不同软件播放

**Comment by Aicirou** [comment]
> windows访问播放目前是iina://weblink?url=
> 可以加个判断windows为potplay嘛 potplayer://
> 类似这个修改版https://github.com/yanzai/goindex 电脑和手机端会自动判断选择不同软件播放

不常用windows，麻烦推荐一下windows支持网络播放的常用播放器，谢谢

**Comment by jzysl123** [comment]
Windows potplayer 不必考虑其他的了

**Comment by Aicirou** [comment]
@jzysl123  potplayer已经支持了

**Comment by jzysl123** [comment]
@Aicirou ipad端打开网页直接是空白显示 不知道哪里的问题

**Comment by Aicirou** [comment]
截图看看

**Comment by zyk445971319** [comment]
请问大佬 搜索中文搜索不到东西 需要怎么才能修复呢？

**Comment by Aicirou** [comment]
> 请问大佬 搜索中文搜索不到东西 需要怎么才能修复呢？

decode的问题，已经解决，如果你使用的是我提供的cdn地址只需要清一下缓存就好了

**Comment by jzysl123** [comment]
![微信图片_20200430135320](https://user-images.githubusercontent.com/51441378/80676543-9335a180-8ae9-11ea-8ad4-38c869fd35fe.png)
@Aicirou

**Comment by jzysl123** [comment]
![12222222](https://user-images.githubusercontent.com/51441378/80676955-78aff800-8aea-11ea-9560-56044d25d602.jpg)

用其它浏览器也一样的空白

**Comment by JokerAB** [comment]
大佬，能否添加nPlayer呢

**Comment by Aicirou** [comment]
@jzysl123 尝试过清理浏览器缓存吗

**Comment by Aicirou** [comment]
> 大佬，能否添加nPlayer呢

转移问题到[#9](https://github.com/Aicirou/goindex-theme-acrou/issues/9)
