### ISSUE TITLE
原作者删了，用不了 你这个我改了app.js 还是不行，可以指点一下吗？谢谢了^-^

### ISSUE THREAD

**Issue by wangchunin** [Aicirou/goindex-theme-acrou#5]

**Comment by Aicirou** [comment]
按照README中的使用步骤修改就可以了

**Comment by wangchunin** [comment]
![image](https://user-images.githubusercontent.com/29172268/80454449-a49d7300-895c-11ea-9a6b-f1ce6dc51773.png)
非常感谢您的回复，我不是做web方面的，可能会犯一些低级错误，我只是修改了这个地方，但是出现404错误
![image](https://user-images.githubusercontent.com/29172268/80454595-e3cbc400-895c-11ea-80e2-be4cdbcdd102.png)

**Comment by wangchunin** [comment]
可以了，非常感谢，404我重新打开cf就没有了，不知道是什么原因
