### ISSUE TITLE
Ads before playing a video are in Chinese

### ISSUE THREAD

**Issue by viper-adnan** [Aicirou/goindex-theme-acrou#78]
Hey, you are doing a great work. I noticed that when I play a video the ad comes while loading the player is in Chinese. Make it as like when we choose language English so the ad is changed to English. You know what I mean.

**Comment by Aicirou** [comment]
No ads.

**Comment by viper-adnan** [comment]
![Screenshot_2020-06-24-10-43-53-070_com android chrome](https://user-images.githubusercontent.com/60770759/85503811-27167c00-b608-11ea-9068-9773a58fbbf2.jpg)
I am talking about this pre video, can you change it to buffering icon or else ? It would be great.

**Comment by dora-admin001** [comment]
I think this is the feature of the video api, not ads (It not sell anythings😂)
You can change it yourself to another video api.

**Comment by viper-adnan** [comment]
> I think this is the feature of the video api, not ads (It not sell anythings😂)
> You can change it yourself to another video api.

How ?
