### ISSUE TITLE
No download button in preview.

### ISSUE THREAD

**Issue by viper-adnan** [Aicirou/goindex-theme-acrou#89]
![Screenshot_2020-06-24-10-43-53-070_com android chrome](https://user-images.githubusercontent.com/60770759/85503644-bff8c780-b607-11ea-8900-6d236dde35e6.jpg)

There is no downlaod button at this page ( if there is it is not clickable) I have to copy the link and open it in new tab. Can you add a downlaod button right to the downlaod link or else. It is great If you change the pre video playing ( see in the screenshot ) to a buffering icon.
Thanks ♥️

**Comment by Aicirou** [comment]
Aicirou/goindex-theme-acrou@a75e1d4c0e5e051250225671ef24ada5b2f7f4b1

**Comment by viper-adnan** [comment]
Thanks bro
